### ISSUE TITLE
Learn from R package `flextable` and other table packages

### ISSUE THREAD

**Issue by pavopax** [Roche/rtables#1]
For ideas and inspirations, you may consider the R package `flextable`. I just found it and drop it here for reference

browsing how they do things may inspire your solutions and/or implementations.

http://www.ardata.fr/blog/2018/01/flextable-0-4-0-is-out/

**Comment by dgkf** [comment]
I've seen flextable pop up a couple times since seeing @pavopax mention it here. I know @waddella has some slightly different objectives (namely introspection of cell values for testing purposes) with rtables, but we should certainly take a serious look at whether those objectives warrant another package. Perhaps we could consider contributing instead to `flextable` or making interoperability with `flextable` a goal.

Any thoughts @waddella?

**Comment by waddella** [comment]
We have now created a number of outputs using rtables and I have been adding features as we needed them. The scope of rtables is still forming. I will document the next release and then we can compare the features/requirements to those of existing table creation/output/tabulation packages.

**Comment by waddella** [comment]
Hello @pavopax and @dgkf,

`rtables` has now quite a few features and with the next release we will add the `format_sprinf` function (thanks @dgkf suggesting that). Also some of the coming features that I plan to add to the projects are documented in [the following presentation](https://docs.google.com/presentation/d/1bpdBDp4PZdZ4hCsfaPkAuHDVnJmtp7WBIZ19oKMDq0M/edit?usp=sharing).

Do you know of any other R project that can create similar tables with the same features (colspans, multi-row header, `rtabulate`, pagination, etc...)? If yes, lets use this issue to show examples of other R packages that provide more powerful ways to work with tables.

Thanks,
Adrian

**Comment by pavopax** [comment]
I recently learned about [tableone](https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html)

**Comment by dgkf** [comment]
The [kableExtra](http://haozhu233.github.io/kableExtra/awesome_table_in_html.html) package covers many of the formatting concerns as well. It covers:

* row indents
* grouped rows
* extensible formatting
* multiple output formats
* table footnotes

It might be considerably easier to build a class wrapper around the source data and the (kableExtra or otherwise) export functions than it would be to continue writing yet another table formatting package.

**Comment by gmbecker** [comment]
Closing as out of date. For discussion of the modern rtables API please start a new issue if desired.
