### ISSUE TITLE
write `tree_structure` as a mix of makepagedf, treestruct, summarize

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#100]
look at makepagedf using visible_only=FALSE

**Comment by gmbecker** [comment]
@waddella make_pagdf now takes a visible_only argument which defaults to TRUE. When it is false, it returns a row for every structural element withint he tree, instead of a row for every visible row when printed.

I've also fixed the path column so that it gives individual rows and content elements the right full pathing to them. I think whatever summary you have in mind can be strictly a display of the full df here, in which case I'd think you can write the wrapper that does that since you seem to have strong thoughts about exactly how it looks. Thoughts?

**Comment by gmbecker** [comment]
superseded by #123
