### ISSUE TITLE
cbind_rtables error

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#142]
Hi @gmbecker, would you please help troubleshoot the code below for cbind_rtables? I think the error may be related to having row splits that don't exist in the analysis data. Is it bad practice to build layouts like this? 

```
df <- data.frame(
  arm = factor(c("A", "B")),
  n = c(101, 102),
  n_rsp = 0.1, 0.2,
  row_type = factor(c("content", "content"), levels = c("content", "analysis")),
  var_label = c("All", "All"),
  stringsAsFactors = FALSE
)

afun_lst <- list(
  n = function(df, labelstr = "", ...) {
    in_rows(.list = as.list(df[["n"]]), .labels = "row1", .formats = "xx")
  },
  n_rsp = function(df, labelstr = "", ...) {
    in_rows(.list = as.list(df[["n_rsp"]]), .labels = "row1", .formats = "xx.x%")
  }
)

# Make simple table.
t1 <- basic_table() %>%
  split_cols_by("arm") %>%
  split_cols_by_multivar(vars = c("n", "n_rsp"), varlabels = c("N", "Rsp %")) %>%
  split_rows_by("row_type", split_fun = keep_split_levels("content"), nested = FALSE, child_labels = "hidden") %>%
  analyze_colvars(afun = afun_lst) %>%
  build_table(df)

# This works.
cbind_rtables(t1, t1)

# Same table visually but now layout has dummy row split + dummy analyze not found in the data.
t2 <- basic_table() %>%
  split_cols_by("arm") %>%
  split_cols_by_multivar(vars = c("n", "n_rsp"), varlabels = c("N", "Rsp %")) %>%
  split_rows_by("row_type", split_fun = keep_split_levels("content"), nested = FALSE, child_labels = "hidden") %>%
  analyze_colvars(afun = afun_lst) %>%
  split_rows_by("row_type", split_fun = keep_split_levels("analysis"), nested = FALSE, child_labels = "hidden") %>%
  split_rows_by(var = "var_label", nested = TRUE) %>%
  analyze_colvars(afun = afun_lst) %>%
  build_table(df)

# This gives an error.
cbind_rtables(t2, t2)
```
This is the error:
```
Error in (new("standardGeneric", .Data = function (..., deparse.level = 1)  : 
  number of columns of matrices must match (see arg 3)
```

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.3.3 magrittr_1.5 

loaded via a namespace (and not attached):
[1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     Rcpp_1.0.4.6    forcats_0.5.0   digest_0.6.25   packrat_0.5.0   rlang_0.4.6     purrr_0.3.4
```

**Comment by gmbecker** [comment]
Generally if the table the comes out is missing pieces taht are defined by the structure of the layout you declared, something bad has happened.

But here's the thing, if we think about the tabulation you're asking rtables to make here, it has the following structure/recipe

Subtable 1:

- "split" on row_type but only the `content` ones
  -  This creates 1 child containing 1 observation
    -   _Within each of these children_ `analyze_ by column`, resulting in 1 row with values in it


Subtable 2
- "split" on `row_type` again, but this time only with `analysis`
  - This creates 1 child **_containing 0 observations_**
  - Within each of these children, further split on `var_label` (which in your code is a character)
    - Create 1 child **_ per value_** of `df$var_label` for a total of **_0 created children_**
      - _Within each of these children_ `analyze_by_column` resulting in ????

So I'd argue this table is at least somewhat conceptually malformed.

Now there were a couple of bugs running around here, but with the fix i pushed above, **if you make var_label a factor** it works including the cbind because then subtable 2 is doing the following instead

- "split" on `row_type` again, but this time only with `analysis`
  - This creates 1 child **_containing 0 observations_**
  - Within each of these children, further split on `var_label`
    - Create 1 child per **_level_** of `df$var_label` for a total of **_1 created child_** containing 0 observations
      - _Within each of these children_ `analyze_by_column` resulting in your function being called with a 0-row df.
        - Your function passes a length 0 list to `in_rows` with a length >0 .labels and .formats. _(this is a bug in the analysis function)_


So if you change your preparatory code to 

```
df <- data.frame(
  arm = factor(c("A", "B")),
  n = c(101, 102),
  n_rsp = c(0.1, 0.2),
  row_type = factor(c("content", "content"), levels = c("content", "analysis")),
  var_label = factor(c("All", "All")),
  stringsAsFactors = FALSE
)

afun_lst <- list(
  n = function(df, labelstr = "", ...) {
    in_rows(.list = as.list(df[["n"]]), .labels = if(nrow(df)) paste0("row", seq_len(nrow(df))), .formats = rep("xx", nrow(df)))
  },
  n_rsp = function(df, labelstr = "", ...) {
    in_rows(.list = as.list(df[["n_rsp"]]), .labels = if(nrow(df)) paste0("row", seq_len(nrow(df))), .formats = rep("xx.x%", nrow(df)))
  }
)
```

This will work. I have pushed a small change that makes the error you would get before changing your afuns more helpful. 

I will think about throwing an error in the original case where the variable you're splitting on is a character and there is 0 data in the parent split, but I want to do some digging first.

**Comment by gmbecker** [comment]
As a further note, I'm tempted to go farther and say that having an analysis function that generates zero rows is an error.  @anajens @danielinteractive do you know of any reason that this could break anything you need? @waddella thoughts?

**Comment by anajens** [comment]
Thanks @gmbecker for the reply! I absolutely agree that this is a strange way to construct a table. 

The use case for this is to make a layout function that sometimes creates a table with only 1 row and sometimes a table that has the following structure:

```
All 
Age Group
  A
  B
  C
...
```
I was not sure how to make the layout conditional on the data except by including the dummy row splits. So for this specific case I think it is useful to have an analysis function generate zero rows. Unless you can suggest an alternative? 

Here is the full example:
```
# Sometimes df will only have the "All" rows
df <- data.frame(
  arm = factor(c("A", "B", "A", "B", "A", "B")),
  n = c(101, 102, 50, 20, 51, 82),
  n_rsp = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6),
  row_type = factor(c("content", "content", rep("analysis", 4)), levels = c("content", "analysis")),
  var_label = factor(c("All", "All", rep("Subgroup 1", 4)), levels = c("All", "Subgroup 1")),
  stringsAsFactors = FALSE
)

lyt <- ?
```
```
# Full table
build_table(lyt, df)

                  A             B     
              N    Rsp %    N    Rsp %
--------------------------------------
All         101    10%    102    20% 
                         
Subgroup 1                            
  row1       50     30%    20     40% 
  row2       51     50%    82     60%
```
```
# It would be nice to be able to use the same layout to make just a subtable 
build_table(lyt, df %>% filter(row_type == "content"))

                  A             B     
              N    Rsp %    N    Rsp %
--------------------------------------
All         101    10%    102    20% 
```

**Comment by gmbecker** [comment]
Layouts are generally going to be deterministic, they are not designed to support data-level conditionality at the level you're lookig for here because they are built prior to the data being available. The way to get the kind of data-conditional layouting that you want is to wrap the construction of the layout in a function that accepts the data.

There are serious downsides to this in terms of complicating the computational model, but it would look something like this:
```
tab_gen_fun <- function(df) {
lyt <- basic_table() %>%
  split_cols_by("arm") %>%
  split_cols_by_multivar(vars = c("n", "n_rsp"), varlabels = c("N", "Rsp %")) %>%
  split_rows_by("row_type", split_fun = keep_split_levels("content"), nested = FALSE, child_labels = "hidden") %>%
  analyze_colvars(afun = afun_lst

if("analysis" %in% df$rowtype) {
  lyt <- lyt %>%
    split_rows_by("row_type", split_fun = keep_split_levels("analysis"), nested = FALSE, child_labels = "hidden") %>%
    split_rows_by(var = "var_label", nested = TRUE) %>%
    analyze_colvars(afun = afun_lst)
}
 build_table(lyt, df)
}
```

Ok, soapbox time.

Note I'm generating `lyt` and then adding to it. The ability to do this is by design, its why I advise strongly against piping all the way into build_table. Its better to create a layout object and then pass it to `build_table`

Also, I know people are going to be tempted to write really complicated functions where most of the logic lives in the function rather than the tabulation.  I believe quite strongly that most of the time this will be a mistake that will end in tears. Resist the impulse as often as you can.  But sometimes you cant, and in those cases, mixing in post-data conditionality is perfectly doable as above.

**Comment by danielinteractive** [comment]
> As a further note, I'm tempted to go farther and say that having an analysis function that generates zero rows is an error. @anajens @danielinteractive do you know of any reason that this could break anything you need? @waddella thoughts?

@gmbecker not sure. I am happy to give it a test run on our internal tests, e.g. if you put a `stopifnot` somewhere that would stop analysis functions generating zero rows. Really hard to say for sure without trying it out.

**Comment by gmbecker** [comment]
I'll discuss it with Adrian today and see what we think.

**Comment by anajens** [comment]
Thanks very much @gmbecker for the suggestions.
