### ISSUE TITLE
add reset_indent_mod

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#171]
Starting with this table: I specify the indentation at the "Mean" rows to align with the "subgroup summary" rows

```
library(rtables)

t1 <- basic_table() %>%
  summarize_row_groups("STUDYID",label_fstr = "overall summary") %>%
  split_rows_by("AEBODSYS",  child_labels = "visible") %>%
  summarize_row_groups("STUDYID", label = "subgroup summary") %>%
  analyze("AGE", indent_mod = -1L) %>%
  build_table(ex_adae)


```

```
                         all obs  
----------------------------------
overall summary        1934 (100%)
  cl A.1                          
    subgroup summary   422 (21.8%)
    Mean                  34.7    
  cl B.1                          
    subgroup summary   178 (9.2%) 
    Mean                  35.86   
  cl B.2                          
    subgroup summary   410 (21.2%)
    Mean                  35.42   
...
```

However, after I trim away the content rows this indentation is re-evaluated and now the "Mean" rows are aligned with the "cl" rows. Is this supposed to happen and if so, is there any way to avoid this?

```
criteria_fun <- function(tr) {
  is(tr, "ContentRow")
}

trim_rows(t1, criteria = criteria_fun)
```

```
         all obs
----------------
cl A.1          
Mean      34.7  
cl B.1          
Mean      35.86 
cl B.2          
Mean      35.42 
cl C.1          
Mean      33.83 
cl C.2          
Mean      33.89 
cl D.1          
Mean      34.39 
cl D.2          
Mean      34.83 
```

**Comment by gmbecker** [comment]
Ok, so the issue here is taht indent)mod is a modifier, not an indentation level, so it modifies whatever the natural/default positioning for the row/table would be. When you remove the content rows, that default position is what changes. You can see this by the fact that if you don't have an indent modifier, those rows still move the same amount (one indent level to the left) when the content rows are removed. They always move to the left one. 

I'm not sure there' a way around this that is going to be easy and do the right thing. @waddella thoughts?

**Comment by anajens** [comment]
Thanks @gmbecker that makes sense.  I thought that after `build_table` is called those indentation relationships would be "fixed" in place but it seems that's not the case.

**Comment by waddella** [comment]
this can be solved by adding a `reset_indent_mod` function 

```r
trim_rows(t1, criteria = criteria_fun) %>%
   reset_indent_mod()
```
