### ISSUE TITLE
Error in `value_at` for layout with overall column

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#172]
It's not possible to extract the cell value using `value_at` when the table layout includes an overall column:

```
library(rtables)

result <- basic_table() %>%
  split_cols_by("ARM") %>%
  analyze(c("AGE", "SEX")) %>%
  build_table(ex_adsl)

# this works
value_at(result, c("AGE", "Mean"), c("ARM", "C: Combination"))

# Now add overall column
result_overall <- basic_table() %>%
  split_cols_by("ARM") %>%
  add_colcounts() %>%
  add_overall_col("ALL") %>%
  analyze(c("AGE", "SEX")) %>%
  build_table(ex_adsl)

# error
value_at(result_overall, c("AGE", "Mean"), c("ARM", "C: Combination"))

```
This is the error:
```
Error in tail(pos_splits(kids[[1]]), 1)[[1]] : subscript out of bounds
```

Session info:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.3.6 magrittr_1.5 

loaded via a namespace (and not attached):
[1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     Rcpp_1.0.4.6    digest_0.6.25   rlang_0.4.9  
```

**Comment by gmbecker** [comment]
@anajens So this is a legitimate bug,  which I am investigating and will fix, but its also (probably) not quite doing what you think it is anyway.

`add_overall_col()` adds a _**top level**_ split which contains all entries, in other words, its not a sibling with the 3 arm value  columns, its actually a sibling with the ARM split that contains those three columns. 

What this means is that your code should work, and it isn't (and I will fix that) but 

```r
value_at(result_overall, c("AGE", "Mean"), c("ARM", "ALL"))
```

will **not** work, even after the fix, as that path would be incorrect for the structure.

This is because `add_overall_col` adds an _overall split_, which is to be contrasted with adding an _overal level_ to a split, which would be done via the `add_overall_level` split function constructor like so

```r
result_overall <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("ALL", first = FALSE)) %>%
  add_colcounts() %>%
  analyze(c("AGE", "SEX")) %>%
  build_table(ex_adsl)
```

The output is visually the same (unfortunate but I think unavoidable), but the column structure is actually different and notably your `value_at()` call does work fine. Also, the ARM->ALL path I mentioned above **is** valid and would work here.

So at the end of the day, this version is probably(?) what you actually wanted, and it does work correctly, but the other version is broken, as you correctly pointed out, and it will get fixed (with the pathing caveat).

**Comment by waddella** [comment]
lets deprecate the `add_colcounts` function on `gabe_tabletree_work`

**Comment by waddella** [comment]
please test if `rbind` is working correctly for this issue

**Comment by anajens** [comment]
@gmbecker this is a related use case that perhaps should be considered when looking into `add_overall` and pathing:

```r
library(rtables)

# 2 levels of nested columns - OK
basic_table() %>%
  split_cols_by(var = "ARM") %>% 
  split_cols_by("STRATA1") %>%
  add_overall_col("All Patients") %>%
  add_colcounts() %>%
  analyze("AGE") %>%
  build_table(ex_adsl)

# 3 levels of nested columns - error
basic_table() %>%
  split_cols_by(var = "ARM") %>% 
  split_cols_by("STRATA1") %>%
  split_cols_by("STRATA2") %>%
  add_overall_col("All Patients") %>%
  add_colcounts() %>%
  analyze("AGE") %>%
  build_table(ex_adsl)

# Error in .do_tbl_h_piece(clyt) : length(unique(lpieces)) == 1 is not TRUE
```

**Comment by gmbecker** [comment]
> @gmbecker this is a related use case that perhaps should be considered when looking into `add_overall` and pathing:
> 
> ```r
> library(rtables)
> 
> # 2 levels of nested columns - OK
> basic_table() %>%
>   split_cols_by(var = "ARM") %>% 
>   split_cols_by("STRATA1") %>%
>   add_overall_col("All Patients") %>%
>   add_colcounts() %>%
>   analyze("AGE") %>%
>   build_table(ex_adsl)
> 
> # 3 levels of nested columns - error
> basic_table() %>%
>   split_cols_by(var = "ARM") %>% 
>   split_cols_by("STRATA1") %>%
>   split_cols_by("STRATA2") %>%
>   add_overall_col("All Patients") %>%
>   add_colcounts() %>%
>   analyze("AGE") %>%
>   build_table(ex_adsl)
> 
> # Error in .do_tbl_h_piece(clyt) : length(unique(lpieces)) == 1 is not TRUE
> ```

This is a separate bug which I will convert into a separate issue. 

For the initial issue,  this is now fixed with both of the following working:
```
> result_overall <- basic_table() %>%
+   split_cols_by("ARM") %>%
+   add_colcounts() %>%
+   add_overall_col("ALL") %>%
+   analyze(c("AGE", "SEX")) %>%
+   build_table(ex_adsl)
> 
> # error
> value_at(result_overall, c("AGE", "Mean"), c("ARM", "C: Combination"))
[1] 35.43182
> value_at(result_overall, c("AGE", "Mean"), c( "ALL"))
[1] 34.875
```
