### ISSUE TITLE
as_html should include tiltes and footnotes

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#205]
The plain text version of this table includes the titles and footnotes, but the html version does not. Is this expected? 

```r
basic_table(title = "ABC", main_footer = "XYZ") %>%
  split_cols_by("ARM") %>%
  analyze("AGE") %>%
  build_table(ex_adsl) %>%
  Viewer()
```

![image](https://user-images.githubusercontent.com/43623360/122318034-75ddb580-ceec-11eb-9169-65046157ecd6.png)

**Comment by gmbecker** [comment]
Depends a bit on what you mean. Its expected, in a way, in that as_html
hasn't been updated to suppor them yet, so it would be pretty surprising
that if they did show up, but that is just a matter of it not having
happened yet, not any sort of intentional design choice that they not be
supported when rendered to HTML.

**Comment by anajens** [comment]
Thanks @gmbecker ! Would be good to add this as an issue for the backlog.

**Comment by gmbecker** [comment]
This is done, at least in gabe_tabletree_work
