### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#229]
Initially reported by @kieranjmartin on Feb 26, 2020 (for initial version of `rtables`)

> 1. Good methods to glue together tables vertically and horizontally
> 2. Ways to handle programmatic inputs, clearly documented (things like rrowl)
> 3. Methods to convert data frames (and other typical objects) into rtables
> 4. Accessor methods for modifying rtables simply
> 5. rtabulate should support multiple splits
> 6. More control over alignment
> 7. Much more sophistication in as_html(), and the ability to modify the html object both before and after without actively rewriting the html code

**Comment by anajens** [comment]
From this list above I think 1-5 have been addressed in the refactored version of `rtables` and 6-7 are still to be done.

**Comment by gmbecker** [comment]
- [ ] Good methods to glue together tables vertically and horizontally
- [ ] Ways to handle programmatic inputs, clearly documented (things like rrowl)
- [ ] Methods to convert data frames (and other typical objects) into rtables
- [ ] Accessor methods for modifying rtables simply
- [ ] rtabulate should support multiple splits
- [ ] More control over alignment
- [ ] Much more sophistication in as_html(), and the ability to modify the html object both before and after without actively rewriting the html code

**Comment by gmbecker** [comment]
@anajens @kieranjmartin

I think direct conversion of a data.frame into an rtables object doesn't make a ton of sense, is that something that is still needed? My guess is that most of the time that would be used was when tabulation/cell-value-creation was done by e.g., dplyr, but the tabulation framework should cover that I think.

I'm also not so sure about the modifying html after calls to as_html thing.  It returns a "shiny.tag" object so is this one already done, since you can manipulate those further?

**Comment by gmbecker** [comment]
I'm going to close this, all of this is done except for (7), which I honestly think is out of scope for us

**Comment by shajoezhu** [comment]
Thanks Gabe!
