### ISSUE TITLE
How to construct a multi col header

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#234]
Issue originally reported by @kieranjmartin

> I know you are encouraged to use the in built arguments to construct a table, but if I wanted to construct a table manually I'm not quite clear on how to do this.
> 
> This works
> 
```
rtable(rheader(rrow(row.name = NULL, rcell("all obs", colspan = 4)), 
               rrow(NULL, "a", "b", "c", "d")),
       rrow("range", 10, 20, 10, 20),
       rrow("number", rcell(20, colspan = 4)))
```

>But this doesn't

```
rtable(rheader(rrow(row.name = NULL, rcell("all obs", colspan = 4))),
       rrow("range", 10, 20, 10, 20),
       rrow("number", rcell(20, colspan = 4)))
```

> The reason seems to be that rheader is collapsing down to one column there, even if it shouldn't. Is there a way to accomplish the latter scenario? Putting a dummy empty row doesn't work either

```
rtable(rheader(rrow(row.name = NULL, rcell("all obs", colspan = 4)), 
              rrow(NULL, "", "", "", "")),
      rrow("range", 10, 20, 10, 20),
      rrow("number", rcell(20, colspan = 4)))
errors.
```

>Also, this actually only errors when you print the object; you can actually create the object, it just won't print successfully, with message
> 
> Error in rbind(header_content$span, body_spans) :
> number of columns of matrices must match (see arg 2)
> 
> This is in version 0.3.8

**Comment by gmbecker** [comment]
hi @anajens @kieranjmartin

I'm a bit confused about the table you're trying to make here. is it something like

```
                      all obs
------------------------------------------------------
range     10         10         10           10
number                   20                                     
```

? If so, no that is not supported. rtables tables have a column tree structure where the column tree is expected to always have leaves that correspond to each of the columns in the data rows of the table. This table doesn't have that structure. Put another way, what would the column paths to identify the positions within this table be?  There aren't any valid ones. And its not just printing, I would expect the column axis subsetting to break as well (exactly how much of it I'm not sure, but I would expect at least anything path based, and possibly the numerical/logical subsetting too)

If you put non-empty values in the second row, say "a", "b", "c", and "d", and have the right number of them then your table works, though obviously then its not your table.

The only thing I know of that you can do to get something like this is make "all obs" a single column (no colspan) and then construct the values you want to show up as strings , one per row. That of course doesn't let you get at the individual values here, but you wouldn't necessarily be able to any way because of the incoherent column structure, I think, so I guess maybe thats not so bad?

But again I kind of have to ask, why do you want a table like that?

**Comment by kieranjmartin** [comment]
Hi @gmbecker I'm not sure I completely follow your terminology here, but I do think this is a coherent table; it has 4 columns and three rows, but in the header and row two, they are collapsed. 

This example came up in a somewhat more complicated case where a user wanted to split out values into value and percentage in seperate columns, while maintaining the header: something like

```
         a                b
--------------------------------------
value   20 30%         40 50%
```
In this case they would then be able to index down to the percentage rather than having to index to the cell then an individual value.

My naïve assumption would be this would be possible; I have 4 columns, and could index numerically if not on name.

**Comment by gmbecker** [comment]
Hi @kieranjmartin,

> My naïve assumption would be this would be possible; I have 4 columns, and could index numerically if not on name.

No that isn't possible. There must be as many (leaf) columns in the column structure as there are entries in the rows.  

Individual cells can be multi-valued, however, so I also don't really understand the desire to do this if its not reflected in  how it is printed.  I think I must still be missing something about the underlying desire here...

**Comment by gmbecker** [comment]
@anajens @kieranjmartin is this still an oustanding hard requirement or can this be closed as wontfix (which is the current status of this issue unless we revisit it)

**Comment by anajens** [comment]
For me, I can't quite see either a use case where it's not sufficient to access the cell which includes both the count and percent.

**Comment by gmbecker** [comment]
I'm going to go ahead and close this. If a real table where this is absolutely necessary comes up we can open a new issue, but the difficulties in doing so are unlikey to change so supporting this will likely require a lot of work.
