### ISSUE TITLE
Possibility of using multiple processing such as mclapply function?

### ISSUE THREAD

**Issue by shajoezhu** [Roche/rtables#259]
Hi @gmbecker , I was wondering is it possible to use multiple processing (mclapply function for example) to improve the rtable performance? 

We are working on refactoring some of the lab tables, and trying to improve speed. I was just wondering if it is possible for us to process the leaf nodes simultaneously? Many thanks!

**Comment by gmbecker** [comment]
This is possible but not guaranteed to show large speed ups necessarily, as in most cases the actual analysis functions are not where most of the time is spent.  I would need to see a realistic table that is too slow and needs to be sped up in order to assess whether this or other optimizations will help with your use case.

**Comment by gmbecker** [comment]
Closing this for now. Will open a new issue if  performance becomes crucial.
