### ISSUE TITLE
Nested parameter FALSE is in Roxygen header vs TRUE in the code

### ISSUE THREAD

**Issue by PaulinCharliquart** [Roche/rtables#264]
Hi,

**nested** parameter is set to `TRUE` in the code (see [here](https://github.com/Roche/rtables/blob/main/R/colby_constructors.R#L326)).
However, in the Roxygen header is set to `FALSE` by default ([here](https://github.com/Roche/rtables/blob/main/R/argument_conventions.R#L56)).

![image](https://user-images.githubusercontent.com/64043642/140970534-b583ae2d-8d9e-4db3-8edf-4c85df1086c9.png)

I am happy to submit a pull request to fix this.  But which one should be fixed?

Kind regards,
Paulin

**Comment by gmbecker** [comment]
Hi Paulin,

Thanks for noticing this. The code is correct. `analyze` calls which appear one after the other default to `TRUE`, and have for some time, rather than `FALSE` as they initially did long ago. (Note this was only ever true of `analyze`, `split_*_by` have always defaulted to `nested = TRUE`

Best,
~G

**Comment by gmbecker** [comment]
Thanks again for this report. Its addressed in the above commit and will percolate outward to the main branch and eventually to CRAN bundled with other further development.
