### ISSUE TITLE
subset removes topleft

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#269]
In `rtables` version ` 0.4.0`

```r
library(rtables)

tbl <- basic_table() %>%
  split_cols_by("Species") %>%
  analyze(c("Sepal.Length", "Sepal.Width"), mean) %>%
  append_topleft("ABC") %>%
  build_table(iris)

tbl[1:2, ]
```
removes the topleft. Thats an issue for pagination. We can either change `paginate` or the subsetting.

**Comment by gmbecker** [comment]
The `[` method for rtables tables accepts a `keep_topleft` argument, which controls this behavior.

By default, for arbitrary subsetting, the default is `FALSE` because typically toplet materials often summarize table/splitting structure, and there is no way to ensure (and one should not expect) that to remain correct after arbitrary subsetting.

That said, `paginate_table` does subsetting with `keep_topleft = TRUE`, so this isn't an issue when using the pagination API fully. It is true that if one does `tt_pag_indices` and then does subsetting on their own, they will need to make sure `keep_topleft` is set to true, but that is by design due to the above consideration.
