### ISSUE TITLE
column path for getting column counts  

### ISSUE THREAD

**Issue by wangh107** [Roche/rtables#319]
Is there a way to access the column counts (big N in column) by column path? 

 ```
                              A: Drug X   B: Placebo   C: Combination
                               (N=121)     (N=106)        (N=129)    
```

**Comment by gmbecker** [comment]
Those Ns are modeled differently than model splits, so instead of using pathing, there is an accessor for them: `col_counts`. Right now, that function doesn't take a pathing argument and always gives the full array back.

Accessing only a subset of them by pathing is an interesting idea, I'll need to think for a bit if that's something we want to support, and how.

**Comment by gmbecker** [comment]
@wangh107 I have added a path argument to the `col_counts` getter (and setter) function, so you can now dow `col_counts(tbl, path = <>)` to specify subsets of the column counts.
