### ISSUE TITLE
`rbind()` of two tables fails because `.ref_full` is different

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#331]
Background: Sometimes we want to `rbind()` two tables that were produced with different data sets. 
Just one example: First table is baseline value summary, second table is model results summary.
Unfortunately this currently fails.

Reprex:
```r
library(rtables)

l1 <- basic_table() %>%
  split_cols_by("ARM", ref_group = "A: Drug X") %>%
  analyze("AGE", afun = list_wrap_x(summary), format = "xx.xx")
d1 <- subset(DM[1:10, ], select = c(ARM, AGE))
t1 <- build_table(l1, d1)
t1

l2 <- basic_table() %>%
  split_cols_by("ARM", ref_group = "A: Drug X") %>%
  analyze("RACE", afun = list_wrap_x(summary), format = "xx.xx")
d2 <- subset(DM[1:10, ], select = c(ARM, RACE))
t2 <- build_table(l2, d2)
t2

t3 <- rbind(t1, t2)
# fails with error in chk_compat_cinfos(x[[1]], xi) : 
# Column structures not compatible: 2nd column structure has non-matching, non-null extra args

# This is only because the ref_full in the column infos is different:
ci1 <- rtables:::col_info(t1)
ex1 <- rtables:::col_extra_args(ci1)

ci2 <- rtables:::col_info(t2)
ex2 <- rtables:::col_extra_args(ci2)

lapply(ex1, "[[", ".ref_full")
lapply(ex2, "[[", ".ref_full")
```

Idea to fix this: `chk_compat_cinfos()`  should not complain about different `.ref_full` in the column infos.

Session Info:
```
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_CH.UTF-8       
 [4] LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.5.1.3  formatters_0.3.1 magrittr_2.0.3  

loaded via a namespace (and not attached):
[1] compiler_4.1.3  fastmap_1.1.0   cli_3.3.0       htmltools_0.5.2 tools_4.1.3     grid_4.1.3     
[7] digest_0.6.28   rlang_1.0.2    
```

**Comment by danielinteractive** [comment]
@gmbecker @waddella Hi Gabe and Adrian, please see this new problem with `rbind()`. Thanks for your help with this.

**Comment by gmbecker** [comment]
Hi @danielinteractive,

So generally any substructure (subtable or row) in an rtables table must have the same column info as its parents, and on up, all the way up to the root table. This is because of the fact that when we subset in  the row dimension, we (generally) select one or more of thse substructures, and *their column info* is used as the column info of the resulting subset table.

With some possible caveats that we'll get to below, this is a very important constraint.

We don't want

`tbl[1,]`  and `tbl[5,]` to have different column structures, from eachother or from `tbl` as a whole.

So now we get to the meat of the issue. How far can the requirements in `chk_compat_cinfos` be relaxed.

There are some requirements that I think are non-negotiable in that regard:

1. if `pth` is a valid column path for `tbl` then it must be a valid path for all possible substructures selected from `tbl` using only row-dimension subsetting.
2. Any information displayed, or which can be displayed, in the column structure portion of the table when printed must apply/be valid for all row-dimension-only substructures. This includes:
     - column labels
     - column counts
3. reference levels must, **at the very least**, not actively mismatch. 
     - Arguably if present and absent that could be ok, but even there its iffy because it seems likely that we'll have the ability to demarcate the ref group in the column header someday.
4. Arguably (but a pretty strong argument), any aspect of the column info whose getter is exported must return answers that match for all rows and row-subset structures of a table

Now would have to look at *exactly* what I have exported and what I dont, with respect to point 4, but I'm sure you can see that that, and even more the 4 requirements taken together, are quite stringent requirements.

Now it is true I could relax some of these, such as the case filed here, and then silently clobber the column info of all arguments to rbind after the first and force the col_info from the first in. 

I'm hesitant to do that automatically.  It is however, quite easy to do manually, because that is what happens when some arguments have no column structure (an artifact of the fact that you can construct rows directly, but a useful one):

In other words, the following will declare that you DO want `b's` column info clobbered, and works now:

```
> col_info(b) <- EmptyColInfo
> rbind(a, b)
                                              A                    B         
                                            (N=18)               (N=18)      
—————————————————————————————————————————————————————————————————————————————
[0,2]                                                                        
  n                                           18                   18        
  Adjusted Mean (SE)                   256.652 (11.859)     264.496 (11.859) 
    95% CI                            (232.993, 280.311)   (240.837, 288.155)
  Difference in Adjusted Means (SE)                          7.844 (16.771)  
    95% CI                                                 (-25.615, 41.303) 
    Relative Increase (%)                                         3.1%       
    p-value (MMRM)                                               0.6415      
(2,4.5]                                                                      
  n                                           18                   18        
  Adjusted Mean (SE)                   288.649 (11.859)     282.992 (11.859) 
    95% CI                            (264.990, 312.308)   (259.333, 306.651)
  Difference in Adjusted Means (SE)                         -5.657 (16.771)  
    95% CI                                                 (-39.116, 27.801) 
    Relative Increase (%)                                        -2.0%       
    p-value (MMRM)                                               0.7369      
(4.5,7]                                                                      
  n                                           18                   18        
  Adjusted Mean (SE)                   312.178 (11.859)     308.518 (11.859) 
    95% CI                            (288.519, 335.837)   (284.859, 332.177)
  Difference in Adjusted Means (SE)                         -3.660 (16.771)  
    95% CI                                                 (-37.119, 29.799) 
    Relative Increase (%)                                        -1.2%       
    p-value (MMRM)                                               0.8279      
(7,9]                                                                        
  n                                           18                   18        
  Adjusted Mean (SE)                   336.630 (11.859)     350.851 (11.859) 
    95% CI                            (312.971, 360.289)   (327.192, 374.510)
  Difference in Adjusted Means (SE)                         14.222 (16.771)  
    95% CI                                                 (-19.237, 47.681) 
    Relative Increase (%)                                         4.2%       
    p-value (MMRM)                                               0.3994      
[0,2]                                                                        
  n                                           18                   0         
  Mean (SD)                              256.7 (32.1)           NA (NA)      
  Median                                    253.4                  NA        
  Min - Max                             199.1 - 321.5           NA - NA      
```

In fact when you do that the rbind is going to be *really* sloppy.  It will end up in practice checking if the number of columns is correct ( though the error is pretty deep and somewhat arcane), but thats **it**.  You don't have to have the same nesting structure, or matching paths, or matching names, or anything.

**Comment by gmbecker** [comment]
I kind of wonder if what you really want, though, is some sort of CompoundTable structure, which is just a list of strictly valid tables which share metadata and are printed together in some reasonable and expected way. 

That would be a non-trivial feature, but is technically and conceptually feasible, I think, if its high enough priority.

**Comment by danielinteractive** [comment]
Thanks a lot @gmbecker ! 
To your last question - yes, I think you would want a `CompoundTable` concept here. And not just for `rbind` but also for a `cbind` I guess. Something to further discuss with @waddella and @shajoezhu etc. re: priorities I would guess.

**Comment by gmbecker** [comment]
Quick note, I dont know how likely it would be in cbind space, but we can
discuss it. On first blush it seems more straightforward, though as I said,
non trivial, for rinds, because relaxing the restraints in controlled
settings makes more sense to me there than in cbinds.

**Comment by gmbecker** [comment]
@danielinteractive Closing this as a wontfix with workaround for now, and I'm going to open a new issue regarding the compound table as a wishlist for investigation/prioritization.
