### ISSUE TITLE
Support different digits in `3d` for `list_valid_format_labels()`

### ISSUE THREAD

**Issue by fb-elong** [Roche/rtables#346]
Could we add different number of digits in `3d`? Currently, it only support two digits. 

```
> list_valid_format_labels()

$`3d`
[1] "xx.xx (xx.xx - xx.xx)"
```

**Comment by gmbecker** [comment]
I've added `"xx. (xx. - xx.)"`, `"xx.x (xx.x - xx.x)"`, and  `"xx.xxx (xx.xxx - xx.xxx)"` to `formatters` (which is where the formatting code actually lives) in  insightsengineering/formatters@3fb2c04818c0d094565b7a32c34d14a673edb6ec


If you need a workaround today that works in, e.g., the CRAN releases of formatters and rtables, you can use `sprintf_format` or a completely custom format function which does whatever you want.

I hope that between the two of them the above are sufficient for your immediate needs.

Beyond that, overhauling the format label system so that there is an actual parser is on the roadmap, but its not currently slated for immediate work, as it is a fairly large undertaking. When that does happen, you'll be able to mix and match as desired.

Closing for now as completed.
