### ISSUE TITLE
Is there a way of just presenting the data as a listing, without doing any summary

### ISSUE THREAD

**Issue by feigs** [Roche/rtables#349]
I am new to the package and maybe I have just not found it, but is there a way of presenting the data in a data frame as-is and just add header and footer? The goal is to prepare a simple listing. I thought that maybe the analyze function could have some sort of identity operation, that would just return the data as a table, without summarizing it. I have tried to create something like that in the code snippet below, but it did not work:

  ```r 
library("tibble")
library("rtables")

set.seed(42)
myTable <- tibble(TREATMENT = rep(c("A","B"),each=6), 
                  SUBJECTID=1:12,
                  AGE = as.integer(runif(12,min=20,max=99)),
                  DTHFL = ifelse(rbinom(12,1,prob=0.1),"Y",""),
                  `FATAL AE` = ifelse(DTHFL=="Y","Progressive Disease","")) 

# define function for showing the data 

showData<-function(df){
  df}

# generate mock table

mock_table <- basic_table() |>
  split_cols_by("TREATMENT") |>
  analyze("TREATMENT",showData)

main_title(mock_table) <- "8.3: Safety Data
XX.XX.X: Deaths, Other Serious and Adverse Events
Table XX.XX.X: Listing of Deaths"

main_footer(mock_table) <- "Source: ADSL - Created DDMONYYYY; Listing YY.Y"

# build table

build_table(mock_table,myTable)
```
Is it currently possible to generate listings with rtables? Is it something that's in the package`s roadmap?

**Comment by gmbecker** [comment]
Hi @feigs,

Due to performance issues, using rtables itself for listings is not really feasible in practice for realistic listsings (1000s or 10000s  of rows). 

That said, we are developing a specialized package (which lives at https://github.com/insightsengineering/rlistings) for listings which will have the formatting, pagination, etc that rtables supports.

Development had been paused on that (which is why that repo appears inactive) but is actually just now restarting active development in the next week or so.

**Comment by feigs** [comment]
Hi @gmbecker ,

thanks, that's good to know. Do you have a rough of the timeline for releasing **rlistings**?

**Comment by gmbecker** [comment]
As its currently scoped, we aim for there to be something releasable within Q1 of 2023.

**Comment by gmbecker** [comment]
Closing this issue as completed. Please watch and discuss on [insightengineering/rlistings](https://github.com/insightsengineering/rlistings) for future development of listing functionality.
