### ISSUE TITLE
refactor `get_formatted_cells`, `RowTable` method to work off CellValue objects directly

### ISSUE THREAD

**Issue by gmbecker** [Roche/rtables#353]
@melkiades Please take a look at this and consider it for a first issue.

Currently, the `RowTable` method for `get_formatted_cells` uses `row_values` to extract the *raw* values from the row's cells, and then later passes them, along with a format and na_str to `format_rcell`. This works but causes annoying regressions whenever we (very occasionally) want to add more information that the CellValue caries around.

`format_rcell`, however, is intended to be able to work directly on the `CellValue` (S3 class for performance reasons, see it's constructor for its details) objects carried around by a table row.

Refactor (and thus simplify) this method so it operates on the CellValue objects.

Note: this will likely involve narrow changes to `format_rcell`, this is ok, but make sure they are backwards compatible.

**Comment by Melkiades** [comment]
Which information do you intend to keep from `CellValue`? As far as I could understand this is what it mainly carries around:
```
## Class definition
## [[1]] list: cell value
## format : format for cell
## colspan: column span info for cell
## label: row label to be used for parent row
## indent_mod: indent modifier to be used for parent row

Browse[3]> str(x)
List of 1
 $ : num 4.4
 - attr(*, "colspan")= int 1
 - attr(*, "indent_mod")= int 0
 - attr(*, "footnotes")= list()
 - attr(*, "class")= chr "CellValue"
 - attr(*, "format")= chr "xx.xx"
```
My plan atm is to use keep them all as attributes, so as to have the result of `get_formatted_cells` identical if no attributes is considered, while it carries the information. Should I replace `rawvalues(x)` which is only doing `x[[1]]` atm with one that keeps the attributes? Otherwise, I will just create one to use _ad hoc_ for `format_rcells`. 

Just a fast Q to understand your coding standard 
- code currently from `setMethod("get_formatted_cells", "TableRow",` etc | - >`val = row_values(obj)`
- my intended change | - > `val = obj@leaf_value`

The change is due to the fact that `row_values` already loses the att info in `get_formatted_cells` and I was thinking if it is better to access the `CellValues` directly trough `@` or by a specific function.

**Comment by gmbecker** [comment]
@Melkiades
There's no reason you would know this if you don't program in S4, but we don't use `@` outside of getter or setter functions, please use `row_cells` to retrieve the list of CellValue objects. In practice that means the `@` should never appear in code (as opposed to in roxygen comments, obviously), outside of `R/tree_accessors.R`. Furthermore, whenever you find yourself wanting access to a slot of a class, look in that file, as there should already by an accessor which gives you what you want.

As far as your other question, we're not talking about changing the `CellValue` "class" currently, just refactoring the method in question to pass them instead of raw values. The reason this is a little tricky is that we need to preserve the default format/na_str behavior.

What it is doing now is grabbing those values off of the TableRow object, and then  superseding them. Part of this task is to figure out a clean way of perserving that behavior when we are passing the `CellValue` objects directly to `format_rcell`
