### ISSUE TITLE
Warning in tests (related to the reference Vignette's fix, i.e. the `[`, `[<-` overloading)

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#392]
I get the below warning at the end of tests (related to current workaround [rtables#362](https://github.com/Roche/rtables/issues/362)):
```
Warning message:
Objects listed as exports, but not present in namespace:
• [
• [<- 
```
And the following at the beginning:
```
Creating a generic function for ‘nrow’ from package ‘base’ in package ‘rtables’
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘rtables’
Creating a generic function for ‘rbind’ from package ‘base’ in package ‘rtables’

Attaching package: ‘dplyr’

The following object is masked from ‘package:testthat’:

    matches

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union
```
This second one is related to our discussion about overloading common functions, and I fully understand the choices that are made, but I think it would be better to go one way or the other, i.e. having all these functions with a suffix or prefix so you know what to look for or they are all overloaded. Still, if the second is the case the NAMESPACE conflicts are quite annoying in my opinion and could be a source of uncaught errors downstream.

**Comment by gmbecker** [comment]
> I get the below warning at the end of tests (related to current workaround [rtables#362](https://github.com/Roche/rtables/issues/362)):
> 
> ```
> Warning message:
> Objects listed as exports, but not present in namespace:
> • [
> • [<- 
> ```
> 


Its strange that our automation is passing. Can you try to figure out why that is (as a warning during tests should cause it to fail). If its real, we'll need to take that workaround for the pkgdown issue out and figure something else out.

> And the following at the beginning:
> 
> ```
> Creating a generic function for ‘nrow’ from package ‘base’ in package ‘rtables’
> Creating a generic function for ‘ncol’ from package ‘base’ in package ‘rtables’
> Creating a generic function for ‘rbind’ from package ‘base’ in package ‘rtables’
> 
> Attaching package: ‘dplyr’
> 
> The following object is masked from ‘package:testthat’:
> 
>     matches
> 
> The following objects are masked from ‘package:stats’:
> 
>     filter, lag
> 
> The following objects are masked from ‘package:base’:
> 
>     intersect, setdiff, setequal, union
> ```
> 
> This second one is related to our discussion about overloading common functions, and I fully understand the choices that are made, but I think it would be better to go one way or the other, i.e. having all these functions with a suffix or prefix so you know what to look for or they are all overloaded. Still, if the second is the case the NAMESPACE conflicts are quite annoying in my opinion and could be a source of uncaught errors downstream.

This is an issue with dplyr and has nothing to do with `rtables` (and the issue has existed since the inception of `dplyr`). There's not really anything we can do about it: If our tests need dplyr (there's no reason they should AFAIK, but some tests are currently written to use them) then we have to load dplyr, which means those symbols are going ot be masked.

Note this doesn't occur when `rtables` is loaded, because we don't have `dplyr` as a `Depends`, only a `Suggests`, so I think this is fine.
