### ISSUE TITLE
change rtable to dataframe

### ISSUE THREAD

**Issue by wang216** [Roche/rtables#7]
# Reporting an Issue with rtables

Hi,

I'm wondering how to convert rtable into data.frame? 

For example, if I created a rtable like this:

```r
library(rtables)
tbl <- rtable(
  header = c("Treatement\nN=100", "Comparison\nN=300"),
  format = "xx (xx.xx%)",
  rrow("A", c(104, .2), c(100, .4)),
  rrow("B", c(23, .4), c(43, .5)),
  rrow(),
  rrow("this is a very long section header"),
  rrow("estimate", rcell(55.23, "xx.xx", colspan = 2)),
  rrow("95% CI", indent = 1, rcell(c(44.8, 67.4), format = "(xx.x, xx.x)", colspan = 2))
)
tbl 
##                                           Treatement        Comparison
##                                             N=100             N=300   
## ----------------------------------------------------------------------
## A                                         104 (20%)         100 (40%) 
## B                                          23 (40%)          43 (50%) 
## 
## this is a very long section header
## estimate                                             55.23            
##   95% CI                                          (44.8, 67.4)        
```
then how can I change tbl as data.frame format with 3 columns?

Thank you so much.

**Comment by wang216** [comment]
@waddella

**Comment by waddella** [comment]
Hi @wang216,

I've added the output from your table to your message. Currently it's not possible to convert an `rtable` object to a `data.frame`. Note from above that this coercion is not a simple one and also not always possible (e.g. for the above example there is obvious `data.frame` that can represent that table.

Please note that `rtables` have the `[(i,j)` accessor function:

```r
tbl[1:2,]
tbl[-1,]
tbl[5,1]
tbl[1,1][2]
```
Does that solve your problem? Otherwise please go into more details of what you are trying to solve.

Best,
Adrian

**Comment by gmbecker** [comment]
Closing as it was related to old version.
