### ISSUE TITLE
`col_counts` are wrong for total column in this example

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#79]
It seems that sometimes the total column count is right, but sometimes not. Here is an example where it is wrong:

```r
library(rtables)

adsl <- ex_adsl
n_per_arm <- table(adsl$ARM)

adcm <- ex_adcm

result <- basic_table() %>%
  split_cols_by(var = "ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
  build_table(adcm, col_counts = n_per_arm)
result
```

Session info:

```r
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.3.2.17.9015 magrittr_1.5         

loaded via a namespace (and not attached):
[1] compiler_3.6.1  htmltools_0.4.0 tools_3.6.1     Rcpp_1.0.3      digest_0.6.23   packrat_0.5.0   rlang_0.4.3     purrr_0.3.3 
```

**Comment by danielinteractive** [comment]
@gmbecker Thanks, makes sense. I guess it would more logical if either
1. The column total is calculated by `rtables` correctly instead of recycling something. (This is what I expect as a result.)
or
2. An error is thrown.

**Comment by gmbecker** [comment]
The col totals aren't named when you pass them (and don't have the option to be because the naming of columns is not trivial in the nested case) so I don't think 1 is feasible.

Also, as a more general point, you should only be overriding the column totals when the automatic totals would be incorrect (ie when N is not the number of rows in the defined split, e.g., patients where rows are events). Otherwise there's no reason to do this and the automatic behavior should be fine. @danielinteractive

**Comment by gmbecker** [comment]
You can now specify a mix of overridden and non-overriden columns by giving NA for the values which should take the defaults. And again one should generally be as conservative as possible in overriding only what you *need* to override, which is why I decided to allow this. 

Giving a vector of the wrong length is now an error.

**Comment by danielinteractive** [comment]
Thanks Gabe, the error is good. However I wonder why passing `NA` does not lead to the correct summation of column counts in this example - I get 1934 instead of 400?

**Comment by gmbecker** [comment]
The all column acts like a column with no subsettting, so the default is that it counts the rows for its (non)subset, just like any other column. It has nothing to do with the any other column.  if you want it to reflect overridden colcounts you have to do the overriding completely, not just give it NA.

This does expose a deeper issue which is that .N_total is going to be wrong (or more accurately correct but not what we want) in cases where columns are not mutually exclusive, but I think for now that will have to stay as is.
